AllCops:
  Excludes:
    - Rakefile
    - vendor/**/*
    - bin/*
    - config/warble.rb

Documentation:
  # don't require classes to be documented
  Enabled: false

Encoding:
  # no need to always specify encoding
  Enabled: false

LineLength:
  # just one more character please
  Max: 80

AlignParameters:
  # allow for multi-line methods to have normal indentation
  EnforcedStyle: with_fixed_indentation

ClassAndModuleChildren:
  # ok to use compact style when modules are predefined
  Enabled: false

MultilineOperationIndentation:
  # allow multi-line statements to align with 2 spaces
  EnforcedStyle: indented
